version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - edgeaia

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - edgeaia
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

networks:
  edgeaia:
