services:
  - type: web
    name: edgeaia-backend
    env: docker
    plan: free
    repo: https://github.com/chanduC10/edgeaia-platform
    branch: main
    rootDir: backend
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /docs
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: edgeaia-frontend
    env: node
    plan: free
    repo: https://github.com/chanduC10/edgeaia-platform
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve out
    staticPublishPath: out
    autoDeploy: true
